apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: trident-csi
  resources:
    requests:
      storage: 10Gi
  dataSource:
    name: mysql-volume-snap-01
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

