apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-fsx
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-fsx
  template:
    metadata:
      labels:
        app: mysql-fsx
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlvol
      volumes:
        - name: mysqlvol
          persistentVolumeClaim:
            claimName: mysql-volume-clone