apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: web-terminal-non-openshift-operators

---  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal
spec:
  channel: fast
  installPlanApproval: Automatic
  name: web-terminal
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: web-terminal.v1.4.0

